apiVersion: v1
kind: Service
metadata:
  name: {name}-locust-master-service
  namespace: {namespace}
spec:
  ports:
    - port: 5557
      name: loc-master-p1
      protocol: TCP
      targetPort: loc-master-p1
    - port: 5558
      name: loc-master-p2
      protocol: TCP
      targetPort: loc-master-p2
  selector:
    app: {name}-locust-master
    type: locust-master