apiVersion: v1
kind: Service
metadata:
  name: {name}-locust-master-service-lb
  namespace: {namespace}
spec:
  ports:
    - port: 8089
      protocol: TCP
      targetPort: 8089
  selector:
    app: {name}-locust-master
    type: locust-master
  type: LoadBalancer